---
title: "Introduction to Machine Learning - Day 3"
output:
  learnr::tutorial:
    theme: cosmo
    css: css/custom.css
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(magrittr)
library(learnr)
# library(testthat)
# devtools::install_github("datacamp/testwhat")
library(testwhat)
library(checkmate)
library(mlr3)
library(mlr3learners)
library(mlr3viz)
library(kknn)
library(e1071)

errorToMessage = function (expr)
{
  e = try(expr = expr, silent = TRUE)
  if (inherits(e, "try-error"))
    return(list(message = attr(e, "condition")$message, correct = FALSE, location = "append"))
  return(NULL)
}

taskChecker = function (task_name)
{
  # Super ugly, but scoping within the Rmds semms weird...
  fun_txt = paste0('
  fun = function (label, user_code, check_code, envir_result, evaluate_result, ...)
  {
    setup_state(sol_code = check_code, stu_code = user_code)
    msg = errorToMessage(expr = {
      ex() %>% check_object("', task_name, '", undefined_msg = "No object \'', task_name,
        '\' found! Please name your task as \'', task_name, '\'.")
    })
    if (! is.null(msg))
      return(msg)

    # Hashing of the data to check independently of column order etc.
    task_processor = "
    task = ', task_name, '
    task_hash = digest::digest(c(
      digest::digest(sort(sapply(task$env$data, digest::digest))),
      class(task),
      digest::digest(task$task.desc$target)
    ))
    "
    setup_state(sol_code = paste0(check_code, task_processor), stu_code = paste0(user_code, task_processor))

    msg = errorToMessage(expr = {
      ex() %>% check_object("task") %>% check_element("task.desc")
      ex() %>% check_object("task") %>% check_element("env")
      ex() %>% check_object("task_hash") %>% check_equal()
    })
    if (! is.null(msg))
      return(msg)

    return(list(message = "Great job! :)", correct = TRUE, location = "append"))
  }
  ')
  eval(parse(text = fun_txt))
  return(fun)
}

learnerChecker = function (learner_name, check_predict_type = FALSE)
{
  if (check_predict_type) {
    def_pred_type_txt = "
    ll_pred_type = learner$predict.type
    "
    check_pred_type_txt = "
    ex() %>% check_object(\"ll_pred_type\") %>% check_equal()
    "
  } else {
    def_pred_type_txt = "\n"
    check_pred_type_txt = "\n"
  }

  # Super ugly, but scoping within the Rmds semms weird...
  fun_txt = paste0('
  fun = function (label, user_code, check_code, envir_result, evaluate_result, ...)
  {
    setup_state(sol_code = check_code, stu_code = user_code)
    msg = errorToMessage(expr = {
      ex() %>% check_object("', learner_name, '", undefined_msg = "No object \'', learner_name,
        '\' found! Please name your learner as \'', learner_name, '\'.")
    })
    if (! is.null(msg))
      return(msg)

    # Hashing of the learner.
    learner_processor = "
    learner = ', learner_name, '
    ll_short_name = learner$short_name
    ll_par_vals = learner$par.vals
    ll_class = class(learner)',
    def_pred_type_txt, '
    "
    setup_state(sol_code = paste0(check_code, learner_processor), stu_code = paste0(user_code, learner_processor))

    msg = errorToMessage(expr = {
      ex() %>% check_object("ll_short_name") %>% check_equal("Have you used the correct learner?")
      ex() %>% check_object("ll_par_vals") %>% check_equal("The chosen hyperparameter aren\'t correct!")
      ex() %>% check_object("ll_class") %>% check_equal()',
      check_pred_type_txt, '
    })
    if (! is.null(msg))
      return(msg)

    return(list(message = "Great job! :)", correct = TRUE, location = "append"))
  }
  ')
  eval(parse(text = fun_txt))
  return(fun)
}

modelChecker = function (model_name, check_pred_type = FALSE)
{
  fun_txt = paste0('
  fun = function (label, user_code, check_code, envir_result, evaluate_result, ...)
  {
    setup_state(sol_code = check_code, stu_code = user_code)
    msg = errorToMessage(expr = {
      ex() %>% check_object("', model_name, '", undefined_msg = "No object \'', model_name,
        '\' found! Please name your model as \'', model_name, '\'.")
    })
    if (! is.null(msg))
      return(msg)

    # Hashing of the model.
    model_processor = "
    model = ', model_name, '
    model_hash = digest::digest(c(
      sort(model$features),
      model$task.desc$target,
      model$task.desc$size,
      model$task.desc$type
    ))
    "
    setup_state(sol_code = paste0(check_code, model_processor), stu_code = paste0(user_code, model_processor))

    msg = errorToMessage(expr = {
      ex() %>% check_object("model_hash") %>% check_equal()
    })
    if (! is.null(msg))
      return(msg)

    model_processor = "
    model = ', model_name, '
    learner = model$learner
    "
    msg = learnerChecker("learner", ', check_pred_type, ')(label, paste0(user_code, model_processor), paste0(check_code, model_processor), envir_result, evaluate_result, ...)
    if (! msg$correct)
      return(msg)

    return(msg)
  }
  ')
  eval(parse(text = fun_txt))
  return(fun)
}
createChecker = function (object_names)
{
  assert_character(object_names)
  fun = paste('
  fun = function (label, user_code, check_code, envir_result, evaluate_result, ...)
  {
    setup_state(sol_code = check_code, stu_code = user_code)

    msg = errorToMessage(expr = {
    ',
    paste(paste0("ex() %>% check_object(\"", object_names, "\") %>% check_equal()"), collapse = "\n      "),
    '
    })
    if (! is.null(msg))
      return(msg)

    return(list(message = "Great job! :)", correct = TRUE, location = "append"))
  }
  ', collapse = "\n")
  eval(parse(text = fun))
  return(fun)
}

options(width = 100)
tutorial_options(exercise.eval = FALSE, exercise.timelimit = 20L)
```


```{r, child="tutorial-evaluation-intro.Rmd"}
```

```{r, child="tutorial-evaluation-measures-regression.Rmd"}
```

```{r, child="tutorial-evaluation-measures-classification.Rmd"}
```

```{r, child="tutorial-evaluation-overfitting-train-test.Rmd"}
```

```{r, child="tutorial-evaluation-resampling.Rmd"}
```